#!/bin/bash

#get current directory
current_dir=`pwd`

# split_traces_dir=$current_dir/splitted_traces

#add timestamp to split_traces_dir
split_traces_dir=$current_dir/traces_`date +%Y%m%d%H%M%S`

mkdir -p $split_traces_dir

awk '!/gsttracer.c|gsttracerrecord.c/' $GST_DEBUG_FILE > $split_traces_dir/filtered.txt

#read value of environment variable GST_TRACERS and split it into an array of tracers
IFS=';' read -ra tracers <<< "$GST_TRACERS"

for trace in "${tracers[@]}"
do
    #check if trace is not graphic and if not, do next line
    if [[ $trace == "graphic" ]]; then
        continue
    fi
    
    cat $split_traces_dir/filtered.txt | grep $trace > $split_traces_dir/$trace.log
done

rm $split_traces_dir/filtered.txt

